version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: "15.0.0"
    steps:
      - checkout
      - run:
          name: Build and test
          command: xcodebuild clean build test -project Airports.xcodeproj -scheme Airports -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
workflows:
  build:
    jobs:
      - build-and-test
